### ISSUE TITLE
Cost much time if file too large

### ISSUE THREAD

**Issue by hanhaoxian** [vim-erlang/vim-erlang-compiler#28]
When I save the file which has 2000+ lines and contain many define, it would block at saving file and I can do nothing.

**Comment by hcs42** [comment]
The plugin calls Erlang's [compile:file][3] function to perform the compilation for the syntax check. Operations like this are blocking operations in Vim. So if Erlang is slow to compile the file, there is not much we can do to make the syntax check less disruptive.

But the good news is that **you can fine tune** when to perform the syntax check. A few possibilities:

1. You can use :ErlangDisableShowErrors, :ErlangEnableShowErrors and :ErlangToggleShowErrors to enable and disable automatic syntax checking when a file is saved. (See the [documentation][2].) For example I have this mapping in ~/.vim/after/ftplugin/erlang.vim:

        noremap <buffer> ,se :ErlangToggleShowErrors<cr>

2. You can comment out the [BufWritePost line][1] from autoload/erlang_compiler.vim, so that syntax checking is not called when a file is saves, and you can use the following command to perform a syntax check when you need it (you would of course create a key mapping for this command):

        call erlang_compiler#AutoRun(expand("<abuf>")+0)

3. If you want to disable the automatic syntax checking feature permanently (and use `:make` to see the errors), you can put `let g:erlang_show_errors = 0` in your vimrc.

[1]: https://github.com/vim-erlang/vim-erlang-compiler/blob/d628934c406f8691db8b925c4e2542f95b7c8bf7/autoload/erlang_compiler.vim#L25
[2]: https://github.com/vim-erlang/vim-erlang-compiler/blob/d628934c406f8691db8b925c4e2542f95b7c8bf7/doc/vim-erlang-compiler.txt#L41
[3]: http://erlang.org/doc/man/compile.html#file-2

**Comment by hanhaoxian** [comment]
@hcs42 thx, even though set up your suggests, it's not help for the compile time, before I use this plugin, I prefer to map key for erlc command, it's more fast but execute external shell.

**Comment by hcs42** [comment]
Hm, I'm a bit surprised that erlc is faster, since we also use Erlang to do the compilation. Can you send an example module which is slow for you when compiling with vim-erlang-compiler, but faster with erlc?

**Comment by hanhaoxian** [comment]
I try it in my company project, it's not good to send the module to you, it's too old to have 2500+ line in a module, with many dependent .hrl files, I map key for the command " erlc -I include  -o ebin  current_file ", and when I try with the less lines files, it works fine.
Do you have some idea for it???

**Comment by hcs42** [comment]
When you do a :make, Vim prints a line like this:

    :!/home/.../vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin ... myfile.erl 2>&1| tee /var/folders/r3/cj0sy26x2kg5bcb9g48btljh0000gn/T/vq4rwHZ/196

Could you run the same command from the terminal? E.g.

    /home/.../vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin ... myfile.erl

I'm wondering if this is also slow. If yes, then we can add some debug printouts to erlang_check to see which part is slow. If no, then the Vim part of the plugin is slow.

**Comment by hanhaoxian** [comment]
When I execute  `:make`  in Vim or execute `/home/.../vim-erlang-compiler/compiler/erlang_check.erl --outdir ebin ... myfile.erl` with `time` command, the time cost is almost same to erlc command, the time result is following:
![image](https://cloud.githubusercontent.com/assets/3611408/16439333/e096b528-3de9-11e6-8b3d-19a83afc6d7a.png)

But if compile the module by save the file, it takes 10 sec about.

**Comment by hanhaoxian** [comment]
I compare it to eclim in eclipse with same module, it cost almost 6+ sec, but eclim work friendly with not blocking other operations, so I wonder if this plugin could run in background when saving file, so that not to block the current window? So that I can code other module and back to see the last file later.

**Comment by hcs42** [comment]
> But if compile the module by save the file, it takes 10 sec about.

That's interesting, I will think about how to measure what Vim and the plugin are doing in the other 5 seconds.

> so I wonder if this plugin could run in background when saving file, so that not to block the current window?

This is a limitation of Vim, not the plugin. Actually, this is one of the major reasons why the [Neovim][1] project was created. Neovim is a fork of Vim that (among other nice features) allows processes to run in the background, and runs syntax checking and make automatically in the background. I don't use Neovim myself, but here is a setup from @sanmiguel using vim-erlang-compiler: https://gist.github.com/sanmiguel/b95f35ec119915fa50d8#file-init-vim-L133-137

[1]: https://neovim.io/

**Comment by hanhaoxian** [comment]
thx, I would try to write `Inotify` and run rebar compile the file if file changing.

**Comment by hanhaoxian** [comment]
@hcs42 I send you a mail with my module.

**Comment by hcs42** [comment]
> @hcs42 I send you a mail with my module.

Thanks, I got it.

**Comment by hcs42** [comment]
>> But if compile the module by save the file, it takes 10 sec about.
>
> That's interesting, I will think about how to measure what Vim and the plugin are doing in the other 5 seconds.

I found out the reason for the speed difference. Due to a bug, the plugin checked the file twice when automatically saving it, that's why it took the double amount of time compared to simply calling `erlc` or `erlang_check.erl`.

I pushed a fix here: https://github.com/hcs42/vim-erlang-compiler/tree/flymake_fix Could you try it?

> thx, I would try to write `Inotify` and run rebar compile the file if file changing.

Could you elaborate on this point? I'm afraid I don't understand how I could use Inotify in this plugin (without changing Vim itself).

**Comment by hanhaoxian** [comment]
Good job, it works.

> Could you elaborate on this point? I'm afraid I don't understand how I could use `Inotify` in this plugin (without changing Vim itself).

I mean, I just execute a external shell which run compile command when the `.hrl` or `.erl` files changed, run this shell at tmux's pane. It's simple but really useful.

More, if it's possible, I think run these check background, and popup quickfix when compile error would more smoothy. But it seem a limitation in Vim just like you ever said.

**Comment by hcs42** [comment]
> Good job, it works.

Thanks, I merged it: https://github.com/vim-erlang/vim-erlang-compiler/pull/30, so I'm closing this ticket.

>> Could you elaborate on this point? I'm afraid I don't understand how I could use `Inotify` in this plugin (without changing Vim itself).
> 
> I mean, I just execute a external shell which run compile command when the `.hrl` or `.erl` files changed, run this shell at tmux's pane. It's simple but really useful.

I see. You might be interested in [the sync project][1], which does something similar. I'm not using it, but if you want to compile files in a way that doesn't give you feedback inside Vim, but in an async way, then it might be useful.

[1]: https://github.com/rustyio/sync

**Comment by hanhaoxian** [comment]
thanks, I will take it.
